# Главный раздел нашего "рецепта"
services:
  # Наш единственный веб-сервис
  - type: web
    # Имя сервиса на платформе Render
    name: lemma-project
    # Указываем, что среда выполнения - это Docker.
    # Render будет искать Dockerfile и использовать его.
    env: docker
    # Тарифный план
    plan: free
    # Путь для проверки "здоровья" сервиса. Render будет периодически
    # делать GET-запрос по этому адресу, чтобы убедиться, что сервис работает.
    healthCheckPath: /