services:
  - type: web
    name: lepko
    env: python
    plan: starter # Убедитесь, что это ваш платный тариф
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: REDIS_URL # Если вы решите использовать Redis
        sync: false