services:
  - type: web
    name: lemma-project
    env: docker
    plan: starter # Используйте ваш платный план
    healthCheckPath: /?lang=ru
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false